### ISSUE TITLE
jQuery tutorial

### ISSUE THREAD

**Issue by deniseyu** [codebar/tutorials#165]
jQuery tutorial tasks (to-do list and color-picker) ramp up in difficulty at a sheer cliff-face instead of a gentle incline. This has resulted in several students being stuck on these tutorials for weeks or even months. It is additionally difficult for coaches to pick up where the student left off the previous week.

I am going to work on a rewrite of one or both of these tutorials, putting this out there to see if anyone else wants to collaborate.

**Comment by lpil** [comment]
I'd also argue that there's more value in teaching vanilla JS than jQuery at such a low level.

**Comment by despo** [comment]
Maybe some extra tutorials before that would be good. Is there something specific - eg DOM manipulation/Conditionals/Selectors that shoudl be practised on more?

**Comment by despo** [comment]
@deniseyu

**Comment by KimberleyCook** [comment]
Just spoke to a student about this issue and she suggested splitting this into 2 tutorials, with more focus on each task. For example, there is a lot of information at the beginning (selectors, attributes ETC) without applying it.

I'd be happy to help contribute to this

**Comment by lpil** [comment]
I must say that I don't like the fact that selectors and doc manipulation are taught using jQuery, and not even mentioned with vanilla Javascript. This was a good idea back when IE6 was a big player, but now we should really be using the standard library and teaching the language itself, rather than a third party library.

It's much easier to learn jQuery after learning Javascript than to learn Javascript after learning jQuery, and your skills will be much more transferable to frameworks and libraries that are not jQuery.

**Comment by knuxus** [comment]
I think its quite a right assumption, @lpil and I think we should try to educate a more broader approach to all of it, not the easiest way only... but showing all the ways.

**Comment by deniseyu** [comment]
re: vanillaJS - I agree that it's worth having more content on DOM manipulation. But enough people are using the jQuery tutorials at the moment that it doesn't make sense to remove and/or completely modify them. if you guys are up for writing a JS selector basics guide, that would be welcome and we can link to it from the jQuery tutorial.

how can Codebar provide support for creating these tutorials? would it be helpful if we designate a day to sit down and work on these together? @lpil @knuxus @KimberleyCook

**Comment by lpil** [comment]
Happy to help in any way I can. Current plan was to work on a Sinatra tut with @deniseyu in the near future.

**Comment by knuxus** [comment]
Just an hour @deniseyu, where we could sit down on gitter/slack/skype , like a montlhy or bi-weekly thing, we chat and do those decisions/adjustments. 

And try to adapt the existing or rewrite and follow certain paths. We can have maybe some public votes for the next tutorials or refining some points of the existing ones, based on most developer friendly and begginer friendly resources out there.

When do you think its possible to arrange an hour like that, @deniseyu , @KimberleyCook , @despo ?

**Comment by knuxus** [comment]
Also this is a useful bit

https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript
