### ISSUE TITLE
Add license! 

### ISSUE THREAD

**Issue by despo** [codebar/tutorials#167]
http://choosealicense.com/
I think GPL as anyone using/distributing this code should follow the same terms.

Any thoughts?

**Comment by despo** [comment]
On second thought a CC license, Attribution-NonCommercial-ShareAlike 4.0 International

http://creativecommons.org/choose/

**Comment by knuxus** [comment]
Yes, go ahead with that one @despo , it suits quite good the whole codebar org

**Comment by knuxus** [comment]
Ive added within the pull request, @despo if you wish to merge.. just go ahead
