### ISSUE TITLE
Sinatra tutorial

### ISSUE THREAD

**Issue by lpil** [codebar/tutorials#172]
Currently there's no information in the tutorials on where to go next for creating a web application, and it seems that many students gravitate towards the confusing behemoth that is rails. I think Sinatra (or similar) is a much better framework to learn with, largely due to it's simplicity and lack of boilerplate.

@deniseyu Shall we write something?

**Comment by deniseyu** [comment]
@lpil I'm up for this. let's plan a time to meet-- I have some time next weekend (not this one, bc of Silicon Milkroundabout)

**Comment by lpil** [comment]
Cool. Shoot me an email and we'll sort something.

**Comment by deniseyu** [comment]
@lpil are you happy to submit the tutorial? :)

**Comment by lpil** [comment]
Not yet! I want to do a bit more on the first part, and then get another couple of parts out. I've been super busy with something and also preparing to go to euro burning man, so haven't been able to get it done, sadly.

It will happen though :)
