### ISSUE TITLE
Command line tutorial

### ISSUE THREAD

**Issue by lpil** [codebar/tutorials#179]
In writing the Sinatra tutorial I've realised that we use the command line kiiind of a lot, even when we;re trying to avoid it.

Would it be good to have a tutorial for this?

Writing one that covers Windows too will be hard.

**Comment by matyikriszta** [comment]
I have created the first in a series of 3 command line tutorials. Please check it out here and provide constructive feedback on it. http://tutorials.codebar.io/command-line/introduction/tutorial.html

**Comment by lpil** [comment]
We really ought to be using pull requests for this...

It looks like a Unix tutorial, but it tells Windows users to use Powershell. I've not used Powershell, is it POSIX compliant? If not, we should make it clear that Powershell users are not to follow this tutorial. Alternatively, we should add instructions for installing Cygwin for Windows users.

Perhaps it would also be good to get the user to open a graphical file manager in the same directory so that they can see the directories and files being created?

I think we should try and explain tab completion, the importance of reading error messages, and why you should never copy and paste commands you don't fully understand into the terminal.

**Comment by matyikriszta** [comment]
Thanks for the feedback @lpil, I agree on using PR’s for these, this tutorial going live without properly being looked at was a minor hiccup on my part. Powershell is POSIX compliant, all these commands should work in PowerShell. I added some more instruction on how to access PowerShell for Windows users, and a warning about using sketchy commands.

I like the idea of the students opening up a GUI and watching the changes on there, let me think about how implement that.

I think tab completion, error messages and could go into a later tutorial, this really is about just getting students starting with typing stuff into the command line and seeing what happens.

Please see PR for the amends #198

**Comment by lpil** [comment]
Great, makes sense :)
