### ISSUE TITLE
HTML tutorials: Getting students' work online

### ISSUE THREAD

**Issue by skattyadz** [codebar/tutorials#222]
In the HTML tutorials, students get to make a page out of nothing and look at it in the browser. While this is definitely quite fun, I remember that the thing that drew me into web dev was how easily I can put my stuff online for everyone to see... Maybe seeing their stuff online could be really rewarding for students too

Both FTP and Git are potential ways to host a site, but each could be introducing too much at this early stage. I was thinking that maybe we make a small tool that students can run in their project folder to upload the contents to the Codebar website / Github Pages / S3 / whatever

What do people think?

**Comment by Charlotteis** [comment]
I think that'd be a really cool idea, would love to hear more about it.

**Comment by christiansherry** [comment]
+1

Perhaps a simple form on a webpage that allows them to upload a zip of their files, and then returns them a url they can view it on. And gives them the ability to repeat the task once it is online once so they can update it.

**Comment by matyikriszta** [comment]
+1 
I do like that idea @skattyadz, maybe with a beginner level explanation of what is happening when they upload their files?

**Comment by skattyadz** [comment]
I did consider uploading a zip, but I'm wary of the security/ops cost. Another option is via the Dropbox API. That might be making an assumption that people have Dropbox etc



— adam

**Comment by KimberleyCook** [comment]
I think asking people to set up a Dropbox account (if they do not have one) is not a bad thing if it means them putting their website online

**Comment by eddiejaoude** [comment]
GitHub Pages is very easily, and all changes are versioned

**Comment by skattyadz** [comment]
Very easy for who? It requires at least basic use of git




One approach is to get them to install the GitHub app, set up a repo, and push through the GUI without understanding git. We should work out whether that's simple enough. My inclination is not



— adam

**Comment by skattyadz** [comment]
My focus is on making it as simple as possible for instant gratification as early as HTML 2 or 3. Using git might add some more concepts or take too much time. One benefit could be that it introduces git at a very basic level that could help when they come to the git tutorial later

**Comment by alexanderkustov** [comment]
Its as easy as getting the branch gh-pages setup, everything else will be treated by github, so I guess we could try to add this extra step in the html tutorials. and see how students adapt to it.

**Comment by chrisnx** [comment]
Yup, lots of security issues, particular that regardless of the method of getting the code online, if its PHP for example its so easy for those files to contain security holes.

Maybe they will need a screening / approval first, but that might also add a step which takes away from the gratifying feeling of getting code online. I guess at the same time though it would highlight the implications of it being almost too easy to do. #thinkingoutloud.

**Comment by skattyadz** [comment]
I think we take the same approach as GitHub pages. Different domain, in fact maybe stick it straight on S3. My concern was mostly in relation to unzipping on a server



— adam

**Comment by fuzzmonkey** [comment]
What about something like https://www.bitballoon.com/ ? The free account lets you upload a static site in a zip archive to a bitballoon subdomain.

**Comment by skattyadz** [comment]
Very cool, @fuzzmonkey!

**Comment by Charlotteis** [comment]
If we want instant gratification, GitHub Pages might be too complex. I know when I first tried GH Pages it was very frustrating.

**Comment by skattyadz** [comment]
https://zeit.co/now

**Comment by skattyadz** [comment]
https://surge.sh

**Comment by Charlotteis** [comment]
GitHub pages has become a little easier due to drag and drop.

**Comment by Charlotteis** [comment]
GitHub pages has become a little easier due to drag and drop, meaning no need to know Git Command line.

**Comment by skattyadz** [comment]
Oh nice

**Comment by mikail1998** [comment]
For that kind of stuff freecodecamp uses codepen.io maybe you should try too...
