### ISSUE TITLE
JS Lesson 4 Exercise 2 - workaround for bug in iOS Safari

### ISSUE THREAD

**Issue by hackscribble** [codebar/tutorials#223]
The CSS file for this exercise is in a Gist (http://www.checkio.org/user/Sim0000/) so I don't think I can raise an issue on it directly ...

In iPhone Safari (and maybe on iPad too), the "genre" buttons are not clickable with the current CSS.  The fix is to add `cursor: pointer;` as follows:

```
#genres li {
    padding: 10px;
    margin: 5px;
    background-color: #5E5A6B;
    color: #ffffff;
    border-radius: 5px;
    cursor: pointer;
}
```

**Comment by despo** [comment]
I updated the gist, thank you @hackscribble 

https://gist.github.com/despo/05cab2f0b38bc02318e7#file-style-css-L65
