### ISSUE TITLE
JavaScript lesson 4 tutorial hack night notes

### ISSUE THREAD

**Issue by samsworldofno** [codebar/tutorials#230]
Some notes in advance of the tutorial hack night:

* Add rested.io/Postman/curl example of an API request. Is the network tab really the easiest way to explain this?
* AJAX explanation - make it clear that although it's for XML, we can use it for JSON and others
* Separate out JSON section on its own - link to JSON site.
* Move async/sync discussion to further down, once promises/jQuery `done` etc is introduced?
* `getGithubInfo` is written before the keybinding that uses it. Switch this around so it's an outside-in approach?
* Publish to github - make it clear that this is more of an optional step? Can be a pain getting github pages working that doesn't aid the student's understanding of JavaScript/APIs
* Length - students never finish this tutorial in the workshop, but often you can get Exercise 2 started. That's actually a good thing - you can start them working on Exercise 2 and give it as homework. Perhaps break it out into a separate "exercise"?

**Comment by jkbits1** [comment]
good points - I've made some notes to bring along tonight

**Comment by KimberleyCook** [comment]
I have a pile of feedback from both students and coaches that I got over the last 2 tutorials to work on too
