### ISSUE TITLE
Update the link to our chat channel in JavaScript lesson 8

### ISSUE THREAD

**Issue by katebee** [codebar/tutorials#266]
Line 4 of the first section:

> To get help outside our sessions, join the codebar channel

Update the link to our chat channel so it directs to the codebar slack
https://codebar.slack.com/messages/general/details/

- Fork the repository
- Create a new branch
- Change the link
- Commit changes
- Open a Pull Request

**Comment by xtroncode** [comment]
I want to do  it.

**Comment by xtroncode** [comment]
xtroncode-patch-1 I have updated the link and opened a PR.

**Comment by KimberleyCook** [comment]
@xtroncode @katebee The link should be https://codebar-slack.herokuapp.com/ as the other one will only work if you are already a member to our Slack channel

**Comment by xtroncode** [comment]
@KimberleyCook @katebee  should I revert the pull request and again make the changes ?

**Comment by katebee** [comment]
@KimberleyCook Thanks, thoughts on the following?

@xtroncode You can revert, or submit a new pull request; I think either would be fine

I think something similar to this (from elsewhere on the codebar site) would be great:
![selection_045](https://cloud.githubusercontent.com/assets/8607683/13373606/32737390-dd64-11e5-8501-70b96042fa35.png)

Maybe the end result could look like:

> To get help outside of our sessions go to [the Slack channel here](https://codebar.slack.com/messages/general/). If you are not on Slack, use [this link](https://codebar-slack.herokuapp.com/) to get an invite.
> 
> You can also send an email to [hello at codebar.io](mailto://hello@codebar.io).
