### ISSUE TITLE
The tutorials really should be using Python 3

### ISSUE THREAD

**Issue by danielquinn** [codebar/tutorials#313]
2.7 is legacy code and all mainstream projects out there have been supporting Python 3 for about a year now.  It'd be a disservice to educate Python newbies on a version that the community has largely left behind.

**Comment by KimberleyCook** [comment]
@danielquinn Absolutely, if you could spare some time to update them we'd really appreciate it.

**Comment by danielquinn** [comment]
Alright, I'll see what I can do this week as I have the time.

**Comment by danielquinn** [comment]
As promised, I've added #314 for this.

**Comment by lwm** [comment]
@alicestrt Looks like someone got there first. Maybe you could also review #314?

Nice job @danielquinn.
