### ISSUE TITLE
Ruby tutorial references nitrous.io which is now discontinued

### ISSUE THREAD

**Issue by octoberclub** [codebar/tutorials#325]
In http://tutorials.codebar.io/ruby/lesson1/tutorial.html. nitrous.io is now discontinued and I had problems installing ruby on my mac from scratch - it pretty much took the whole session at codebar to resolve. Can we instead look into supplying a VM with ruby set up and instructions on how to use it? e.g. Vagrant?

**Comment by notwaving** [comment]
I can recommend Cloud9.

**Comment by matyikriszta** [comment]
I've used Cloud9 before and it was pretty good, @notwaving do you want to make a PR for this, replacing the nitrous link with a link to Cloud9?

**Comment by notwaving** [comment]
Sure, Kriszta!

I'm away from my laptop today, but I'll get into it this afternoon/evening.

Samantha

**Comment by notwaving** [comment]
Hopefully that went OK. I created PRs for index.html and index.pt
(Portuguese?), as HTML was otherwise identical...

**Comment by matyikriszta** [comment]
Yep, all good, thanks for the PR. Addressed by #336. Closing.
