### ISSUE TITLE
Set up instructions: remove Nitrous or replace with alternative

### ISSUE THREAD

**Issue by SteveBarnett** [codebar/tutorials#350]
Helloes. 👋 😺 

In the [ruby section of the setup tutorial](http://tutorials.codebar.io/general/setup/tutorial.html#ruby-optional) we suggest using a Nitrous. Unfortunately, it shut down on November 14th, 2016. 

[Cloud9](https://c9.io/) seems to be a popular alternative and has a free tier. Should we update the instructions to suggest C9 (or some other cloud IDE) instead of Nitrous?

**Comment by SteveBarnett** [comment]
Ooh, I see we already suggest in on http://tutorials.codebar.io/ for the PHP course. :)

**Comment by matyikriszta** [comment]
@SteveBarnett I have updated every mention of nitrous to cloud9, as per #351. Going to close this issue.
