### ISSUE TITLE
Accessibility tutorial?

### ISSUE THREAD

**Issue by malevolentninja** [codebar/tutorials#371]
Hey all, I am going through the code bar tutorials and was wondering if anyone has considered creating a tutorial to understand how to develop with accessibility in mind ?  For example the uses of ARIA and other attributes. Or at least providing documentation on this? (WCAG and ARIA guidelines). 

I would be keen to work on this with a bit of help!

**Comment by KimberleyCook** [comment]
Morning, @malevolentninja I'm not sure we would need a whole tutorial for this, however I do agree it would be nice to have something. How about we add a bit to the end of tutorial 6 ?

**Comment by malevolentninja** [comment]
@KimberleyCook  thanks for a quick reply! That would be a great place, maybe a bonus section =  'Accessibility Bonus' ? We could have a couple of examples and things to consider when building a web page e.g. font size, alt tags etc. Finally what are your thoughts on adding some documentation links for people to investigate further if they want?

**Comment by KimberleyCook** [comment]
I'm all for a "Further Reading" section too. It was something I started adding in some of the earlier HTML tutorials. Take a look at that format and follow them :)

**Comment by malevolentninja** [comment]
Awesome, will put a few things in first and then look forward to any suggestions of other bits to cover! :)

**Comment by richardwestenra** [comment]
Fixed in #372 🎉
