### ISSUE TITLE
Integrate Twitter login

### ISSUE THREAD

**Issue by khamiltonuk** [codebar/tutorials#393]
I feel it's very important to insure the bar for entry to participate in codebar is as low as possible. 

GitHub has worked well for us, and many beginners have managed to sign up but I feel it has the potential to alienate people who don't know what it is. I also like it because it also as it is very appropriate single sign on platform  given what we do.

My next platform would be Twitter especially over Facebook, I am open to suggestions.

**Comment by despo** [comment]
Hi @khamiltonuk - there is already an issue addressing this on the main repo github https://github.com/codebar/planner/issues/702 

Maybe this can be discussed further there.

**Comment by khamiltonuk** [comment]
Sorry, will try and give it a go
