### ISSUE TITLE
HTML tutorial 5 has an incorrect instruction re background images

### ISSUE THREAD

**Issue by hlb89** [codebar/tutorials#412]
Hi there!
I noticed with a student the other day that HTML tutorial 5 says the following:

> First let’s set two background images, the first positioned on the right and the second on the left.
> background: url('assets/images/background-right.jpg') right top no-repeat,
>             url('assets/images/background-left.jpg') left no-repeat;

This doesn't seem to correspond with the directory structure of the example files, so the student initially got quite confused. Suggest either changing the instructions or changing the directory structure of the example files to match. 

Happy to do this myself with permission!

**Comment by hlb89** [comment]
Had a look at this here:
https://github.com/codebar/tutorials/pull/413

**Comment by KimberleyCook** [comment]
Thank you @hlb89
