### ISSUE TITLE
Heroku app to get a Slack invite appears to be down

### ISSUE THREAD

**Issue by rvedotrc** [codebar/tutorials#418]
In http://tutorials.codebar.io/js/lesson8/tutorial.html, "If you are not on Slack, use this link to get an invite." ( https://codebar-slack.herokuapp.com/ )

which doesn't appear to be working. I'm don't have a suggested replacement link, sorry.

**Comment by matyikriszta** [comment]
@rvedotrc good catch, the new link is https://slack.codebar.io/

**Comment by pmansukhani** [comment]
I'm new to open source. I can take this up. Is there anywhere I can find the guidelines to submit a PR ?

**Comment by matyikriszta** [comment]
@pmansukhani please do. There's no contributing guideline for this repo I'm afraid. Feel free to ask any questions as you go along.

**Comment by pmansukhani** [comment]
@matyikriszta I've created a PR.

**Comment by matyikriszta** [comment]
Thank you @pmansukhani, I've merged it in.
