### ISSUE TITLE
CSS animations, transitions

### ISSUE THREAD

**Issue by despo** [codebar/tutorials#97]
Create new tutorial on CSS animations and transitions.

**Comment by jakehills** [comment]
@knuxus Is this still being looked at? I wouldn't mind writing these.

**Comment by matyikriszta** [comment]
Hi @jakehills,

Yes, this is still being looked at, it would be great if you could help out. Maybe you could put together an outline and we could take it from there?

**Comment by knuxus** [comment]
Hey @jakehills outline that I had previously written for this was.

1. Show some example for animating various elements like titles, images, circles etc on a simple static page. Can be used with this library http://daneden.github.io/animate.css/ but better to write our own.

2. Explain the keyframes with some basic transform animation.
3. Explain the animation properties. basically every parameter of this line

    animation: [animation-name] [animation-duration] [animation-timing-function]
[animation-delay] [animation-iteration-count] [animation-direction]
[animation-fill-mode] [animation-play-state];

4. Animation delay and animation iteration, animation direction.
5. Multiple animations

**Comment by KimberleyCook** [comment]
@knuxus This is something I am super keen to help on

**Comment by knuxus** [comment]
If you want to setup like a one hour chat & write session im all up for it.

cheers
